deployments:
  deploymentGating:
    enabled: true # to enable the feature
    environments: # select the environments you'd like to use with this feature
    - development
    - production
    - staging
    - testing
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzYxOTJjMDM3LWUwZTQtNGRlMS04MWIzLTdkN2VjODk4YzA0MC8wNWNiZTVmZS1iYTllLTExZWYtOTQyZC0xMjAxZjE2ZWQ0MWY=