name: Auto Merge PR

on:
  repository_dispatch:
    types: [jira-approval]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Inputs
        run: |
          echo "Owner: ${{ github.event.client_payload.owner }}"
          echo "Repo: ${{ github.event.client_payload.repo }}"
          echo "Pull Number: ${{ github.event.client_payload.pull_number }}"
      - name: Merge PR
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo, pull_number } = context.payload;
            await github.pulls.merge({
              owner,
              repo,
              pull_number
            });
